bounds update; fix a couple of links in readme
bdaiinstitute/spatialmath-python pull request #108
Opened 2023-12-01 21:06 UTC by jcao-bdai

2023-12-04 07:33 UTC, petercorke commented on spatialmath/quaternion.py
I have a problem with the fix for `log` since `s` can be negative, so the s/|q| should be bounded in the range [-1, 1]. I think the other fixes are ok.

2023-12-05 16:40 UTC, myeatman-bdai requested changes
Small change.

2023-12-05 16:40 UTC, myeatman-bdai commented on tests/test_quaternion.py
> +        self.assertTrue(isscalar(q1.log().s))
Do we need to test `isscalar` and `isvector` twice?

2023-12-05 16:53 UTC, jcao-bdai commented on tests/test_quaternion.py
> +        self.assertTrue(isscalar(q1.log().s))
right! repetitive tests removed, in 811ac8da0ab294a01adcf0abaf6ce5ff038723d5

2023-12-05 20:22 UTC, jcao-bdai commented on tests/test_quaternion.py
> +        self.assertTrue(isscalar(q1.log().s))
could you please take another look? @myeatman-bdai (i can't seem to re-request review from the UI...)

2023-12-05 20:42 UTC, myeatman-bdai approved these changes
Bueno

2023-12-05 20:49 UTC, merged