[Issue-122] Pass shortest arg for interp; optionally enforce non-negative scalar …
bdaiinstitute/spatialmath-python pull request #123
Opened 2024-05-05 14:29 UTC by jcao-bdai

Implements changes from discussions under Issue 122.

2024-05-13 12:52 UTC, myeatman-bdai requested changes

2024-05-13 13:03 UTC, jcao-bdai commented on spatialmath/base/transforms2d.py
> +                delta = (th1 - th0 + math.pi) % (math.pi * 2) - math.pi
found an existing function - updates are pushed in e83f30ee106e455e6625660aeff4d4d075bc7247

2024-05-13 14:27 UTC, myeatman-bdai approved these changes
Thanks!

2024-05-13 14:27 UTC, merged

2025-01-09 00:36 UTC, petercorke commented
Sorry not to have piped up earlier.  I think the option for `r2q` shouldn't be called `shortest`.  Shortest makes sense when talking about a direction around a great circle, but here the option would be better called `positive`.  But it might be better to discard the option entirely, and always return the quaternion with positive scalar.  Since `e` and `-e` are the same rotation, there is nothing wrong making this call.