[SW-235] Added a copy_from method to copy inputs instead of just passing by re…
bdaiinstitute/spatialmath-python pull request #83
Opened 2023-06-29 17:02 UTC by bhung-bdai

…ference to SE3

2023-06-30 13:40 UTC, myeatman-bdai approved these changes
There are some unit tests for this class, could we add a unit test for this function to `test_pose3d.py`

2023-06-30 13:41 UTC, myeatman-bdai commented
Looks good other wise.

2023-06-30 13:42 UTC, myeatman-bdai requested changes

2023-06-30 13:42 UTC, myeatman-bdai commented on spatialmath/pose3d.py
> +    def CopyFrom(
Unit tests

2023-06-30 18:05 UTC, bhung-bdai commented on spatialmath/pose3d.py
> +    def CopyFrom(
Added! Thanks for the notice

2023-06-30 18:05 UTC, bhung-bdai commented
Added unit testing. Should be good to go!

2023-07-05 11:45 UTC, myeatman-bdai commented
Thanks!

2023-07-05 11:45 UTC, myeatman-bdai approved these changes

2023-07-05 11:45 UTC, merged