[SW-237] Raises error if a number of arguments besides 1 and 3 are passed in to SE3 constructors
bdaiinstitute/spatialmath-python pull request #84
Opened 2023-06-29 17:30 UTC by bhung-bdai

Decided not to assign default args in the event of something like (x, y) being passed in because default values aren't specified

2023-06-30 13:43 UTC, myeatman-bdai requested changes

2023-06-30 13:43 UTC, myeatman-bdai commented on spatialmath/pose3d.py
> +        else:
Unit test in `test_pose3d.py`

2023-06-30 17:53 UTC, bhung-bdai commented
I've went ahead and added two tests, confirming they both work with the locally built package.

2023-07-05 11:48 UTC, myeatman-bdai approved these changes
Looks good to me

2023-07-05 11:48 UTC, merged

2023-07-05 11:53 UTC, myeatman-bdai commented
For posterity, the reason for this change was that you could invoke the SE3 constructor as so `SE3(1.0, 0.0)` and get uninitialized values for the internal data.